# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79bb70089d24c961d74cf530e404dd7741a96294539b6554801ab1e0e275efd80da38dcd7afd3978c8b2cb1b7e534af98d0c7a95c1df7c32dc3b34fcded4bb62

test:
  secret_key_base: 4e749969234d7806bbcc984664d287cc5bfd0cad1fd5a7610749e1cdfa2ecb4aeb477609b6a17cf0bbd42cabd7c9dc36ec259c991354ec45a3ff49a8bfa2a265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
